default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>
  host: <%= ENV["DATABASE_HOST"] || "postgres_db" %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] || "backend_production" %>

cable:
    <<: *default
    database: <%= ENV["CABLE_DATABASE_NAME"] || "backend_cable_production" %>

queue:
    <<: *default
    database: <%= ENV["QUEUE_DATABASE_NAME"] || "backend_queue_production" %>

cache:
    <<: *default
    database: <%= ENV["CACHE_DATABASE_NAME"] || "backend_cache_production" %>
