# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Hostname of the database server (in Docker, this should match the service name in docker-compose.yml)
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: 5432
  # Database username (using 'postgres' as per Docker POSTGRES_USER)
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  # Database password (provided via environment variable in docker-compose.yml)
  password: <%= ENV["DATABASE_PASSWORD"] || "root" %>
  # Name of the database to connect to
  database: <%= ENV["DATABASE_NAME"] || "backend_development" %>

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] || "backend_production" %>
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "root" %>

  # Add cable DB config for ActionCable or solid_cable gem
  cable:
    <<: *default
    database: <%= ENV["CABLE_DATABASE_NAME"] || "backend_production_cable" %>
    username: <%= ENV["DATABASE_USER"] || "postgres" %>
    password: <%= ENV["DATABASE_PASSWORD"] || "root" %>
