version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: backend_production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: azizomri/backend-app-ruby:latest
    container_name: backend_app
    depends_on:
      - postgres_db
    environment:
      DATABASE_HOST: postgres_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
      DATABASE_NAME: backend_production
      RAILS_ENV: production
      SECRET_KEY_BASE: 69ecb84c96c9b7fa1af9e61cd83e1fa5a854c2acc3268ccd20acddd41fd5a99785d0a0e7118b522a6809e1b9c50dcd1e3da1d8fb418b884b20a06551c581a788
      MISTRAL_API_URL: https://openrouter.ai/api/v1/chat/completions
      MISTRAL_API_KEY: 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
      MISTRAL_API_KEY_CV_PARSING: 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
    ports:
      - "3000:3000"

  frontend:
    image: azizomri/frontend-app-angular:latest
    container_name: hr_frontend
    ports:
      - "4200:80"

volumes:
  postgres_data: