class SessionsController < Devise::SessionsController
  respond_to :json

  def create
    user = User.find_by(email: params[:user][:email])

    unless user
      return render json: {
        message: 'Sign in failed.',
        errors: ['Email not found']
      }, status: :unauthorized
    end

    unless user.active?
      return render json: {
        message: 'Your account has been banned. Please contact administration.',
        errors: ['Account is inactive']
      }, status: :forbidden
    end

    # Devise authentication
    self.resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)

    # Increment login count
    resource.increment_login_count

    # JWT generated by devise-jwt
    token = request.env['warden-jwt_auth.token']

    # Return full user info + token for Angular
    render json: {
      message: 'Signed in successfully.',
      user: {
        id: resource.id,
        name: resource.name,
        email: resource.email,
        role: resource.role,
        image: resource.image || 'uploads/profile_pictures/default.jpg',
        nbCnx: resource.nbCnx,
        gender: resource.gender || '',
        birth_date: resource.birth_date,
        nationality: resource.nationality || '',
        created_at: resource.created_at,
        updated_at: resource.updated_at
      },
      token: token
    }, status: :ok
  end

  # JWT revocation on logout
  def destroy
    if current_user
      current_user.update(jti: SecureRandom.uuid)
    end
    render json: { message: 'Signed out successfully.' }, status: :ok
  end

  # Optional fallback
  def respond_to_on_destroy
    render json: { message: 'Signed out successfully.' }, status: :ok
  end
end
